services:
  - type: web
    name: topper
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: "https://topper-g651.onrender.com"
